### ISSUE TITLE
Prevent horizontal scrolling in main report pane

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#16]
Currently text in the main report pane does not wrap, but instead allows horizontal scrolling.  We should prevent any horizontal scrolling of the main pane by wrapping the text.  

The HTML tables that will not fit should allow horizontal scrolling of just the particular table.

**Comment by TobiTenno** [comment]
I thought we did this already?

**Comment by jkuester** [comment]
We never really finished it.  

Originally we were waiting to get the tables into real HTML tables, but once that was done we did not come back through and complete the css for everything.  

Basically, what is left is setting up the css for the`<table>` and `<pre>` blocks (for the feature/scenario descriptions and doc strings) so that those individual elements can be horizontally scrolled.  Right now the `<pre>` blocks still cause the whole pane to scroll while the `<table>` elements actually compress to fit.  I don't think we want either of these behaviors.
