### ISSUE TITLE
Is it possible to embed icons in report instead of loading from CDN?

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#22]
Currently the generated reports rely on two types of externally hosted data:
- Google Fonts
- Font Awesome icons (loaded from CloudFlare)

The fonts I am not so worried about because if the external font is not accessible the report will be displayed with the default system fonts.

The icons, on the other hand, worry me a bit more.  At this point they are all aesthetic, and you can use the report fine without them.  However, I expect that in the future we may want to include more icons that may be more functionally important.  (e.g. a button for the settings drawer)

Of, course I am not worried about the icons not being available on CloudFlare in the short-term. My concern is that reports used in an enterprise process have the potential of being around for a _very_ long time (5+ years).  Unlike a normal hosted webpage or application, we would not be able to do anything about already generated reports if the Font Awesome URL ever changed.  (Can, of course, change it for new reports going forwards, but not for any that were previously generated).  

So, we need to investigate the possibility of somehow embedding the icons with the report.  (First thing that comes to mind is encoding them in b64 like we do with the favicon, but maybe there is a better way...)

**Comment by jkuester** [comment]
So, after some experimentation, I can confirm that embedding a base64 image into the HTML should work fine.  (Thanks to @TobiTenno for pointing me to http://fatopng.com/fontawesome-to-base64). That makes it easy to get the base64 text for a FontAwsome icon.  I am working on a PR now to embed the settings cog icon.  Just wanted to record a couple of other thoughts here for posterity sake:

The FontAwsome icon _files_ are licensed under CC BY 4.0 (https://fontawesome.com/license/free). They are free to use but we need to give credit and provide a link to the license. I plan to include this as part of my PR.

Also, it is probably worth noting that we really only need to embed resources for things that are functionally essential.  If the report is still usable without the resource it is probably okay to load it from the web (e.g. I don't see any reason to stop using web-based fonts since the browser can always fall back to the system defaults)

**Comment by TobiTenno** [comment]
Sounds like a great plan.
