### ISSUE TITLE
Show Tags In Report

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#23]
It would be nice to be able to see all of a tags for a feature/scenario in the report.  However since this information might only be useful in select cases, the user should be able to toggle the visibility of the tags (defaulting to not displaying them).  

Here is a mocked up report that I have put together as an example: 
[cucumber-forge-desktop.zip](https://github.com/cerner/cucumber-forge-report-generator/files/3770131/cucumber-forge-desktop.zip)

**Comment by jkuester** [comment]
@TobiTenno can you have a look at my mock-up when you get the chance?

**Comment by TobiTenno** [comment]
I think raising something above the footer instead of raising the footer would be better.

**Comment by jkuester** [comment]
Okay so I did some reworking so that our sidebar header and footer are fixed (and don't scroll) and then I just pop the setting up above the footer. Seems to work pretty well.  @TobiTenno the only thing that I cannot figure out is the best way to get it so that my mouse cursor switches to the little pointy hand when mousing over the FontAwesome settings wheel...  Any thoughts on that would be great!
[cucumber-forge-desktop_large.zip](https://github.com/cerner/cucumber-forge-report-generator/files/3800695/cucumber-forge-desktop_large.zip)

**Comment by TobiTenno** [comment]
For that you just need to `cursor: pointer` in the case for the cog

**Comment by jkuester** [comment]
Nice, that works!
