### ISSUE TITLE
Support nesting the feature buttons in the sidebar according to their folder structure

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#35]
For projects with lots of feature files, things can become confusing quickly when all of the feature buttons are displayed in a flat list. It would be nice to be able to break them up according to the folder structure.

**Comment by jkuester** [comment]
This seems like a good starting point [1].  I think we are going to have to ultimately do away with the padded buttons in the sidebar in favor of a more space-saving nested list....

**Comment by TobiTenno** [comment]
I like the idea, would give us a good chance to rethink the styling on the buttons as well, to be a bit clearer
