### ISSUE TITLE
Support linking to sub-headers within the report

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#40]
Not sure how hard this would actually be to implement, but it would be nice to be able to link to specific sub-headers within a report (such as a feature/scenario title). This would make it easier to reference specific parts of a report.

I am specifically thinking of something similar to the way markdown allows you to link to sub-sections....

**Comment by TobiTenno** [comment]
if they're stored in a common location, it's simply a matter of using the built-in ids when opening the file, it's not really something we need to apply extra logic to get working
