### ISSUE TITLE
Need to handle comments in the feature files (by ignoring them?)

### ISSUE THREAD

**Issue by jkuester** [cerner/cucumber-forge-report-generator#7]
Currently comments are getting pulled in as part of the scenario text. Probably should just ignore those lines.

**Comment by TobiTenno** [comment]
like the docstring, or what kind of comments?

we could add a formatted section that calls it out as a comment, too.

**Comment by jkuester** [comment]
I don't think we actually want to include the comments in the report since they are not really official doc.  Just need to gracefully ignore them.

**Comment by beersonthewall** [comment]
Fixed in this [pull request](https://github.com/cerner/cucumber-forge-report-generator/pull/10).
